global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rtsp_to_redis"
    static_configs:
      - targets: ["rtsp_to_redis:8001"]

  - job_name: "video_analyzer"
    static_configs:
      - targets: ["video_analyzer:8002"]